theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/MineralsCloud/QuantumESPRESSOCommands.jl/archive/refs/tags/v0.3.0.zip
  tar_url: https://github.com/MineralsCloud/QuantumESPRESSOCommands.jl/archive/refs/tags/v0.3.0.tar.gz
